[package]
name = "gars"
version = "0.1.0"
description = "Google Authenticator CLI."
authors = ["shane <shane@digitalsanctum.com>"]
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/digitalsanctum/gars/"

[dependencies]
google-authenticator = "0.3.0"
